namespace ForzaCryptoTool;

internal sealed record LanguageOption(string Code, string DisplayName);

internal static class Localization
{
    public const string DefaultLanguageCode = "en-US";

    public static readonly LanguageOption[] SupportedLanguages =
    {
        new(DefaultLanguageCode, "English"),
        new("zh-CN", "简体中文"),
        new("fr-FR", "Français"),
        new("es-ES", "Español"),
        new("de-DE", "Deutsch"),
        new("it-IT", "Italiano"),
        new("pt-PT", "Português"),
        new("nl-NL", "Nederlands"),
        new("pl-PL", "Polski"),
    };

    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new(StringComparer.OrdinalIgnoreCase)
    {
        [DefaultLanguageCode] = Map(
            ("App.SettingsTitle", "{0} - Settings"),
            ("Nav.Dashboard", "Dashboard"),
            ("Nav.SaveSwap", "Save Swap"),
            ("Nav.ProfileEditor", "Profile Editor"),
            ("Nav.OlderForzaTech", "Older ForzaTech"),
            ("Nav.Settings", "Settings"),
            ("Top.Settings", "Settings"),
            ("Top.AboutTooltip", "About ForzaCryptoTool"),
            ("Top.BackendChecking", "Backend - Checking"),
            ("Top.BackendConnected", "Backend - Connected {0}ms"),
            ("Top.BackendOffline", "Backend - Offline"),
            ("Top.AdminElevated", "Admin - Elevated"),
            ("Top.AdminStandard", "Admin - Not elevated"),
            ("Settings.Backend", "Backend"),
            ("Settings.Endpoint", "Endpoint"),
            ("Settings.TestConnection", "Test"),
            ("Settings.Source", "Source: {0}."),
            ("Settings.AppKey", "App Key"),
            ("Settings.ClearKey", "Clear Key"),
            ("Settings.OutputFolder", "Output Folder"),
            ("Settings.Browse", "Browse"),
            ("Settings.Storage", "Storage"),
            ("Settings.Output", "Output"),
            ("Settings.LanguageCard", "Language"),
            ("Settings.Language", "Language"),
            ("Settings.Updates", "Updates"),
            ("Settings.AutoUpdates", "Automatically check for updates on startup"),
            ("Settings.CurrentVersion", "Current version: {0}"),
            ("Settings.CheckNow", "Check Now"),
            ("Settings.Advanced", "Advanced"),
            ("Settings.ConnectionStatus", "Connection Status"),
            ("Settings.NotChecked", "Not checked"),
            ("Settings.Latency", "Latency"),
            ("Settings.LastHealthCheck", "Last Health Check"),
            ("Settings.Save", "Save"),
            ("Settings.Cancel", "Cancel"),
            ("Settings.ResetEndpoint", "Reset Endpoint"),
            ("Settings.Checking", "Checking..."),
            ("Settings.Connected", "Connected"),
            ("Settings.Unreachable", "Unreachable"),
            ("Settings.Offline", "Offline"),
            ("Dash.DropPrimary", "Drop file here"),
            ("Dash.DropSecondary", "or click to browse  -  GameDB (.slt)  -  Profile Data  -  auto-detected"),
            ("Dash.FileInformation", "File Information"),
            ("Dash.Type", "Type"),
            ("Dash.Status", "Status"),
            ("Dash.Filename", "Filename"),
            ("Dash.Integrity", "Integrity"),
            ("Dash.Size", "Size"),
            ("Dash.Modified", "Modified"),
            ("Dash.NoFile", "No file loaded - drop a GameDB, Profile, Method 22 asset ZIP, or ini file above."),
            ("Dash.Actions", "Actions"),
            ("Dash.Decrypt", "Decrypt"),
            ("Dash.ReEncrypt", "Re-Encrypt"),
            ("Dash.Merge", "Merge"),
            ("Dash.Export", "Export"),
            ("Dash.Output", "Output"),
            ("Dash.MergeTip", "Apply another decrypted GameDB's changes into this one."),
            ("Dash.JobStatus", "Job Status"),
            ("Dash.Idle", "Idle - waiting for a file."),
            ("Dash.Results", "Results"),
            ("Dash.Mode", "Mode"),
            ("Dash.Warnings", "Warnings"),
            ("Dash.NoResults", "No operation completed yet."),
            ("Dash.RecentFiles", "Recent Files"),
            ("Dash.ActivityLog", "Activity Log"),
            ("Dash.ClearLog", "Clear log"),
            ("Dash.SaveLog", "Save log to file"),
            ("Dash.CopyLog", "Copy log to clipboard"),
            ("Dash.NoRecent", "(no recent files)")),

        ["zh-CN"] = Map(
            ("App.SettingsTitle", "{0} - 设置"), ("Nav.Dashboard", "仪表盘"), ("Nav.SaveSwap", "存档替换"),
            ("Nav.ProfileEditor", "档案编辑器"), ("Nav.OlderForzaTech", "旧版 ForzaTech"), ("Nav.Settings", "设置"),
            ("Top.Settings", "设置"), ("Top.AboutTooltip", "关于 ForzaCryptoTool"), ("Top.BackendChecking", "后端 - 检查中"),
            ("Top.BackendConnected", "后端 - 已连接 {0}ms"), ("Top.BackendOffline", "后端 - 离线"),
            ("Top.AdminElevated", "管理员 - 已提升"), ("Top.AdminStandard", "管理员 - 未提升"),
            ("Settings.Backend", "后端"), ("Settings.Endpoint", "端点"), ("Settings.TestConnection", "测试"),
            ("Settings.Source", "来源: {0}."), ("Settings.AppKey", "应用密钥"), ("Settings.ClearKey", "清除密钥"),
            ("Settings.OutputFolder", "输出文件夹"), ("Settings.Browse", "浏览"), ("Settings.Storage", "存储"),
            ("Settings.Output", "输出"), ("Settings.LanguageCard", "语言"), ("Settings.Language", "语言"),
            ("Settings.Updates", "更新"), ("Settings.AutoUpdates", "启动时自动检查更新"),
            ("Settings.CurrentVersion", "当前版本: {0}"), ("Settings.CheckNow", "立即检查"),
            ("Settings.Advanced", "高级"), ("Settings.ConnectionStatus", "连接状态"), ("Settings.NotChecked", "未检查"),
            ("Settings.Latency", "延迟"), ("Settings.LastHealthCheck", "上次健康检查"), ("Settings.Save", "保存"),
            ("Settings.Cancel", "取消"), ("Settings.ResetEndpoint", "重置端点"), ("Settings.Checking", "检查中..."),
            ("Settings.Connected", "已连接"), ("Settings.Unreachable", "无法连接"), ("Settings.Offline", "离线"),
            ("Dash.DropPrimary", "将文件拖到这里"),
            ("Dash.DropSecondary", "或点击浏览  -  GameDB (.slt)  -  档案数据  -  自动检测"),
            ("Dash.FileInformation", "文件信息"), ("Dash.Type", "类型"), ("Dash.Status", "状态"),
            ("Dash.Filename", "文件名"), ("Dash.Integrity", "完整性"), ("Dash.Size", "大小"),
            ("Dash.Modified", "修改时间"), ("Dash.NoFile", "未加载文件 - 请在上方放入 GameDB、档案、Method 22 ZIP 或 ini 文件。"),
            ("Dash.Actions", "操作"), ("Dash.Decrypt", "解密"), ("Dash.ReEncrypt", "重新加密"),
            ("Dash.Merge", "合并"), ("Dash.Export", "导出"), ("Dash.Output", "输出"),
            ("Dash.MergeTip", "将另一个已解密 GameDB 的更改应用到当前文件。"),
            ("Dash.JobStatus", "任务状态"), ("Dash.Idle", "空闲 - 正在等待文件。"),
            ("Dash.Results", "结果"), ("Dash.Mode", "模式"), ("Dash.Warnings", "警告"),
            ("Dash.NoResults", "尚未完成任何操作。"), ("Dash.RecentFiles", "最近文件"),
            ("Dash.ActivityLog", "活动日志"), ("Dash.ClearLog", "清除日志"),
            ("Dash.SaveLog", "保存日志到文件"), ("Dash.CopyLog", "复制日志到剪贴板"),
            ("Dash.NoRecent", "(没有最近文件)")),

        ["fr-FR"] = Map(
            ("App.SettingsTitle", "{0} - Paramètres"), ("Nav.Dashboard", "Tableau de bord"), ("Nav.SaveSwap", "Échange"),
            ("Nav.ProfileEditor", "Éditeur de profil"), ("Nav.OlderForzaTech", "Ancien ForzaTech"), ("Nav.Settings", "Paramètres"),
            ("Top.Settings", "Paramètres"), ("Top.AboutTooltip", "À propos de ForzaCryptoTool"), ("Top.BackendChecking", "Backend - Vérification"),
            ("Top.BackendConnected", "Backend - Connecté {0}ms"), ("Top.BackendOffline", "Backend - Hors ligne"),
            ("Top.AdminElevated", "Admin - Élevé"), ("Top.AdminStandard", "Admin - Standard"),
            ("Settings.Backend", "Backend"), ("Settings.Endpoint", "Point de terminaison"), ("Settings.TestConnection", "Tester"),
            ("Settings.Source", "Source : {0}."), ("Settings.AppKey", "Clé d'application"), ("Settings.ClearKey", "Effacer la clé"),
            ("Settings.OutputFolder", "Dossier de sortie"), ("Settings.Browse", "Parcourir"), ("Settings.Storage", "Stockage"),
            ("Settings.Output", "Sortie"), ("Settings.LanguageCard", "Langue"), ("Settings.Language", "Langue"),
            ("Settings.Updates", "Mises à jour"), ("Settings.AutoUpdates", "Vérifier automatiquement les mises à jour au démarrage"),
            ("Settings.CurrentVersion", "Version actuelle : {0}"), ("Settings.CheckNow", "Vérifier"), ("Settings.Advanced", "Avancé"),
            ("Settings.ConnectionStatus", "État de connexion"), ("Settings.NotChecked", "Non vérifié"), ("Settings.Latency", "Latence"),
            ("Settings.LastHealthCheck", "Dernier contrôle"), ("Settings.Save", "Enregistrer"), ("Settings.Cancel", "Annuler"),
            ("Settings.ResetEndpoint", "Réinitialiser"), ("Settings.Checking", "Vérification..."), ("Settings.Connected", "Connecté"),
            ("Settings.Unreachable", "Injoignable"), ("Settings.Offline", "Hors ligne"),
            ("Dash.DropPrimary", "Déposez le fichier ici"), ("Dash.DropSecondary", "ou cliquez pour parcourir  -  GameDB (.slt)  -  Données de profil  -  détection automatique"),
            ("Dash.FileInformation", "Informations fichier"), ("Dash.Type", "Type"), ("Dash.Status", "État"),
            ("Dash.Filename", "Nom du fichier"), ("Dash.Integrity", "Intégrité"), ("Dash.Size", "Taille"),
            ("Dash.Modified", "Modifié"), ("Dash.NoFile", "Aucun fichier chargé - déposez un GameDB, profil, ZIP Method 22 ou fichier ini ci-dessus."),
            ("Dash.Actions", "Actions"), ("Dash.Decrypt", "Déchiffrer"), ("Dash.ReEncrypt", "Rechiffrer"),
            ("Dash.Merge", "Fusionner"), ("Dash.Export", "Exporter"), ("Dash.Output", "Sortie"),
            ("Dash.MergeTip", "Appliquer les changements d'un autre GameDB déchiffré à celui-ci."),
            ("Dash.JobStatus", "État du travail"), ("Dash.Idle", "Inactif - en attente d'un fichier."),
            ("Dash.Results", "Résultats"), ("Dash.Mode", "Mode"), ("Dash.Warnings", "Avertissements"),
            ("Dash.NoResults", "Aucune opération terminée."), ("Dash.RecentFiles", "Fichiers récents"),
            ("Dash.ActivityLog", "Journal d'activité"), ("Dash.ClearLog", "Effacer le journal"),
            ("Dash.SaveLog", "Enregistrer le journal"), ("Dash.CopyLog", "Copier le journal"),
            ("Dash.NoRecent", "(aucun fichier récent)")),

        ["es-ES"] = Map(
            ("App.SettingsTitle", "{0} - Configuración"), ("Nav.Dashboard", "Panel"), ("Nav.SaveSwap", "Guardados"),
            ("Nav.ProfileEditor", "Editor de perfil"), ("Nav.OlderForzaTech", "ForzaTech antiguo"), ("Nav.Settings", "Configuración"),
            ("Top.Settings", "Configuración"), ("Top.AboutTooltip", "Acerca de ForzaCryptoTool"), ("Top.BackendChecking", "Backend - Comprobando"),
            ("Top.BackendConnected", "Backend - Conectado {0}ms"), ("Top.BackendOffline", "Backend - Sin conexión"),
            ("Top.AdminElevated", "Admin - Elevado"), ("Top.AdminStandard", "Admin - Estándar"),
            ("Settings.Backend", "Backend"), ("Settings.Endpoint", "Endpoint"), ("Settings.TestConnection", "Probar"),
            ("Settings.Source", "Origen: {0}."), ("Settings.AppKey", "Clave de app"), ("Settings.ClearKey", "Borrar clave"),
            ("Settings.OutputFolder", "Carpeta de salida"), ("Settings.Browse", "Examinar"), ("Settings.Storage", "Almacenamiento"),
            ("Settings.Output", "Salida"), ("Settings.LanguageCard", "Idioma"), ("Settings.Language", "Idioma"),
            ("Settings.Updates", "Actualizaciones"), ("Settings.AutoUpdates", "Buscar actualizaciones al iniciar"),
            ("Settings.CurrentVersion", "Versión actual: {0}"), ("Settings.CheckNow", "Buscar ahora"), ("Settings.Advanced", "Avanzado"),
            ("Settings.ConnectionStatus", "Estado de conexión"), ("Settings.NotChecked", "No comprobado"), ("Settings.Latency", "Latencia"),
            ("Settings.LastHealthCheck", "Última comprobación"), ("Settings.Save", "Guardar"), ("Settings.Cancel", "Cancelar"),
            ("Settings.ResetEndpoint", "Restablecer"), ("Settings.Checking", "Comprobando..."), ("Settings.Connected", "Conectado"),
            ("Settings.Unreachable", "Inaccesible"), ("Settings.Offline", "Sin conexión"),
            ("Dash.DropPrimary", "Suelta el archivo aquí"), ("Dash.DropSecondary", "o haz clic para examinar  -  GameDB (.slt)  -  Datos de perfil  -  detección automática"),
            ("Dash.FileInformation", "Información del archivo"), ("Dash.Type", "Tipo"), ("Dash.Status", "Estado"),
            ("Dash.Filename", "Nombre"), ("Dash.Integrity", "Integridad"), ("Dash.Size", "Tamaño"),
            ("Dash.Modified", "Modificado"), ("Dash.NoFile", "No hay archivo cargado - suelta arriba un GameDB, perfil, ZIP Method 22 o archivo ini."),
            ("Dash.Actions", "Acciones"), ("Dash.Decrypt", "Descifrar"), ("Dash.ReEncrypt", "Re-cifrar"),
            ("Dash.Merge", "Fusionar"), ("Dash.Export", "Exportar"), ("Dash.Output", "Salida"),
            ("Dash.MergeTip", "Aplicar los cambios de otro GameDB descifrado a este."),
            ("Dash.JobStatus", "Estado del trabajo"), ("Dash.Idle", "Inactivo - esperando un archivo."),
            ("Dash.Results", "Resultados"), ("Dash.Mode", "Modo"), ("Dash.Warnings", "Advertencias"),
            ("Dash.NoResults", "Aún no se completó ninguna operación."), ("Dash.RecentFiles", "Archivos recientes"),
            ("Dash.ActivityLog", "Registro de actividad"), ("Dash.ClearLog", "Borrar registro"),
            ("Dash.SaveLog", "Guardar registro"), ("Dash.CopyLog", "Copiar registro"),
            ("Dash.NoRecent", "(sin archivos recientes)")),

        ["de-DE"] = Map(
            ("App.SettingsTitle", "{0} - Einstellungen"), ("Nav.Dashboard", "Dashboard"), ("Nav.SaveSwap", "Save-Tausch"),
            ("Nav.ProfileEditor", "Profil-Editor"), ("Nav.OlderForzaTech", "Älteres ForzaTech"), ("Nav.Settings", "Einstellungen"),
            ("Top.Settings", "Einstellungen"), ("Top.AboutTooltip", "Über ForzaCryptoTool"), ("Top.BackendChecking", "Backend - Prüfung"),
            ("Top.BackendConnected", "Backend - Verbunden {0}ms"), ("Top.BackendOffline", "Backend - Offline"),
            ("Top.AdminElevated", "Admin - Erhöht"), ("Top.AdminStandard", "Admin - Standard"),
            ("Settings.Backend", "Backend"), ("Settings.Endpoint", "Endpunkt"), ("Settings.TestConnection", "Testen"),
            ("Settings.Source", "Quelle: {0}."), ("Settings.AppKey", "App-Schlüssel"), ("Settings.ClearKey", "Schlüssel löschen"),
            ("Settings.OutputFolder", "Ausgabeordner"), ("Settings.Browse", "Durchsuchen"), ("Settings.Storage", "Speicher"),
            ("Settings.Output", "Ausgabe"), ("Settings.LanguageCard", "Sprache"), ("Settings.Language", "Sprache"),
            ("Settings.Updates", "Updates"), ("Settings.AutoUpdates", "Beim Start automatisch nach Updates suchen"),
            ("Settings.CurrentVersion", "Aktuelle Version: {0}"), ("Settings.CheckNow", "Jetzt prüfen"), ("Settings.Advanced", "Erweitert"),
            ("Settings.ConnectionStatus", "Verbindungsstatus"), ("Settings.NotChecked", "Nicht geprüft"), ("Settings.Latency", "Latenz"),
            ("Settings.LastHealthCheck", "Letzte Prüfung"), ("Settings.Save", "Speichern"), ("Settings.Cancel", "Abbrechen"),
            ("Settings.ResetEndpoint", "Zurücksetzen"), ("Settings.Checking", "Prüfung..."), ("Settings.Connected", "Verbunden"),
            ("Settings.Unreachable", "Nicht erreichbar"), ("Settings.Offline", "Offline"),
            ("Dash.DropPrimary", "Datei hier ablegen"), ("Dash.DropSecondary", "oder klicken zum Durchsuchen  -  GameDB (.slt)  -  Profildaten  -  automatische Erkennung"),
            ("Dash.FileInformation", "Dateiinformationen"), ("Dash.Type", "Typ"), ("Dash.Status", "Status"),
            ("Dash.Filename", "Dateiname"), ("Dash.Integrity", "Integrität"), ("Dash.Size", "Größe"),
            ("Dash.Modified", "Geändert"), ("Dash.NoFile", "Keine Datei geladen - oben GameDB, Profil, Method-22-ZIP oder ini-Datei ablegen."),
            ("Dash.Actions", "Aktionen"), ("Dash.Decrypt", "Entschlüsseln"), ("Dash.ReEncrypt", "Neu verschlüsseln"),
            ("Dash.Merge", "Zusammenführen"), ("Dash.Export", "Exportieren"), ("Dash.Output", "Ausgabe"),
            ("Dash.MergeTip", "Änderungen einer anderen entschlüsselten GameDB auf diese anwenden."),
            ("Dash.JobStatus", "Auftragsstatus"), ("Dash.Idle", "Leerlauf - wartet auf Datei."),
            ("Dash.Results", "Ergebnisse"), ("Dash.Mode", "Modus"), ("Dash.Warnings", "Warnungen"),
            ("Dash.NoResults", "Noch keine Operation abgeschlossen."), ("Dash.RecentFiles", "Letzte Dateien"),
            ("Dash.ActivityLog", "Aktivitätsprotokoll"), ("Dash.ClearLog", "Protokoll löschen"),
            ("Dash.SaveLog", "Protokoll speichern"), ("Dash.CopyLog", "Protokoll kopieren"),
            ("Dash.NoRecent", "(keine letzten Dateien)")),

        ["it-IT"] = Map(
            ("App.SettingsTitle", "{0} - Impostazioni"), ("Nav.Dashboard", "Dashboard"), ("Nav.SaveSwap", "Scambio"),
            ("Nav.ProfileEditor", "Editor profilo"), ("Nav.OlderForzaTech", "Vecchio ForzaTech"), ("Nav.Settings", "Impostazioni"),
            ("Top.Settings", "Impostazioni"), ("Top.AboutTooltip", "Informazioni su ForzaCryptoTool"), ("Top.BackendChecking", "Backend - Controllo"),
            ("Top.BackendConnected", "Backend - Connesso {0}ms"), ("Top.BackendOffline", "Backend - Offline"),
            ("Top.AdminElevated", "Admin - Elevato"), ("Top.AdminStandard", "Admin - Standard"),
            ("Settings.Backend", "Backend"), ("Settings.Endpoint", "Endpoint"), ("Settings.TestConnection", "Test"),
            ("Settings.Source", "Origine: {0}."), ("Settings.AppKey", "Chiave app"), ("Settings.ClearKey", "Cancella chiave"),
            ("Settings.OutputFolder", "Cartella output"), ("Settings.Browse", "Sfoglia"), ("Settings.Storage", "Archiviazione"),
            ("Settings.Output", "Output"), ("Settings.LanguageCard", "Lingua"), ("Settings.Language", "Lingua"),
            ("Settings.Updates", "Aggiornamenti"), ("Settings.AutoUpdates", "Controlla aggiornamenti all'avvio"),
            ("Settings.CurrentVersion", "Versione attuale: {0}"), ("Settings.CheckNow", "Controlla ora"), ("Settings.Advanced", "Avanzate"),
            ("Settings.ConnectionStatus", "Stato connessione"), ("Settings.NotChecked", "Non controllato"), ("Settings.Latency", "Latenza"),
            ("Settings.LastHealthCheck", "Ultimo controllo"), ("Settings.Save", "Salva"), ("Settings.Cancel", "Annulla"),
            ("Settings.ResetEndpoint", "Reimposta"), ("Settings.Checking", "Controllo..."), ("Settings.Connected", "Connesso"),
            ("Settings.Unreachable", "Non raggiungibile"), ("Settings.Offline", "Offline"),
            ("Dash.DropPrimary", "Rilascia il file qui"), ("Dash.DropSecondary", "o fai clic per sfogliare  -  GameDB (.slt)  -  Dati profilo  -  rilevamento automatico"),
            ("Dash.FileInformation", "Informazioni file"), ("Dash.Type", "Tipo"), ("Dash.Status", "Stato"),
            ("Dash.Filename", "Nome file"), ("Dash.Integrity", "Integrità"), ("Dash.Size", "Dimensione"),
            ("Dash.Modified", "Modificato"), ("Dash.NoFile", "Nessun file caricato - rilascia sopra GameDB, profilo, ZIP Method 22 o file ini."),
            ("Dash.Actions", "Azioni"), ("Dash.Decrypt", "Decifra"), ("Dash.ReEncrypt", "Ricifra"),
            ("Dash.Merge", "Unisci"), ("Dash.Export", "Esporta"), ("Dash.Output", "Output"),
            ("Dash.MergeTip", "Applica a questo file le modifiche di un altro GameDB decifrato."),
            ("Dash.JobStatus", "Stato processo"), ("Dash.Idle", "Inattivo - in attesa di un file."),
            ("Dash.Results", "Risultati"), ("Dash.Mode", "Modalità"), ("Dash.Warnings", "Avvisi"),
            ("Dash.NoResults", "Nessuna operazione completata."), ("Dash.RecentFiles", "File recenti"),
            ("Dash.ActivityLog", "Registro attività"), ("Dash.ClearLog", "Cancella registro"),
            ("Dash.SaveLog", "Salva registro"), ("Dash.CopyLog", "Copia registro"),
            ("Dash.NoRecent", "(nessun file recente)")),

        ["pt-PT"] = Map(
            ("App.SettingsTitle", "{0} - Definições"), ("Nav.Dashboard", "Painel"), ("Nav.SaveSwap", "Troca de save"),
            ("Nav.ProfileEditor", "Editor de perfil"), ("Nav.OlderForzaTech", "ForzaTech antigo"), ("Nav.Settings", "Definições"),
            ("Top.Settings", "Definições"), ("Top.AboutTooltip", "Sobre o ForzaCryptoTool"), ("Top.BackendChecking", "Backend - A verificar"),
            ("Top.BackendConnected", "Backend - Ligado {0}ms"), ("Top.BackendOffline", "Backend - Offline"),
            ("Top.AdminElevated", "Admin - Elevado"), ("Top.AdminStandard", "Admin - Normal"),
            ("Settings.Backend", "Backend"), ("Settings.Endpoint", "Endpoint"), ("Settings.TestConnection", "Testar"),
            ("Settings.Source", "Fonte: {0}."), ("Settings.AppKey", "Chave da app"), ("Settings.ClearKey", "Limpar chave"),
            ("Settings.OutputFolder", "Pasta de saída"), ("Settings.Browse", "Procurar"), ("Settings.Storage", "Armazenamento"),
            ("Settings.Output", "Saída"), ("Settings.LanguageCard", "Idioma"), ("Settings.Language", "Idioma"),
            ("Settings.Updates", "Atualizações"), ("Settings.AutoUpdates", "Procurar atualizações ao iniciar"),
            ("Settings.CurrentVersion", "Versão atual: {0}"), ("Settings.CheckNow", "Verificar"), ("Settings.Advanced", "Avançado"),
            ("Settings.ConnectionStatus", "Estado da ligação"), ("Settings.NotChecked", "Não verificado"), ("Settings.Latency", "Latência"),
            ("Settings.LastHealthCheck", "Última verificação"), ("Settings.Save", "Guardar"), ("Settings.Cancel", "Cancelar"),
            ("Settings.ResetEndpoint", "Repor"), ("Settings.Checking", "A verificar..."), ("Settings.Connected", "Ligado"),
            ("Settings.Unreachable", "Inacessível"), ("Settings.Offline", "Offline"),
            ("Dash.DropPrimary", "Largue o ficheiro aqui"), ("Dash.DropSecondary", "ou clique para procurar  -  GameDB (.slt)  -  Dados de perfil  -  deteção automática"),
            ("Dash.FileInformation", "Informação do ficheiro"), ("Dash.Type", "Tipo"), ("Dash.Status", "Estado"),
            ("Dash.Filename", "Nome do ficheiro"), ("Dash.Integrity", "Integridade"), ("Dash.Size", "Tamanho"),
            ("Dash.Modified", "Modificado"), ("Dash.NoFile", "Nenhum ficheiro carregado - largue acima GameDB, perfil, ZIP Method 22 ou ficheiro ini."),
            ("Dash.Actions", "Ações"), ("Dash.Decrypt", "Desencriptar"), ("Dash.ReEncrypt", "Reencriptar"),
            ("Dash.Merge", "Unir"), ("Dash.Export", "Exportar"), ("Dash.Output", "Saída"),
            ("Dash.MergeTip", "Aplicar a este ficheiro as alterações de outro GameDB desencriptado."),
            ("Dash.JobStatus", "Estado da tarefa"), ("Dash.Idle", "Inativo - à espera de ficheiro."),
            ("Dash.Results", "Resultados"), ("Dash.Mode", "Modo"), ("Dash.Warnings", "Avisos"),
            ("Dash.NoResults", "Nenhuma operação concluída."), ("Dash.RecentFiles", "Ficheiros recentes"),
            ("Dash.ActivityLog", "Registo de atividade"), ("Dash.ClearLog", "Limpar registo"),
            ("Dash.SaveLog", "Guardar registo"), ("Dash.CopyLog", "Copiar registo"),
            ("Dash.NoRecent", "(sem ficheiros recentes)")),

        ["nl-NL"] = Map(
            ("App.SettingsTitle", "{0} - Instellingen"), ("Nav.Dashboard", "Dashboard"), ("Nav.SaveSwap", "Save wisselen"),
            ("Nav.ProfileEditor", "Profieleditor"), ("Nav.OlderForzaTech", "Oude ForzaTech"), ("Nav.Settings", "Instellingen"),
            ("Top.Settings", "Instellingen"), ("Top.AboutTooltip", "Over ForzaCryptoTool"), ("Top.BackendChecking", "Backend - Controleren"),
            ("Top.BackendConnected", "Backend - Verbonden {0}ms"), ("Top.BackendOffline", "Backend - Offline"),
            ("Top.AdminElevated", "Admin - Verhoogd"), ("Top.AdminStandard", "Admin - Standaard"),
            ("Settings.Backend", "Backend"), ("Settings.Endpoint", "Endpoint"), ("Settings.TestConnection", "Testen"),
            ("Settings.Source", "Bron: {0}."), ("Settings.AppKey", "App-sleutel"), ("Settings.ClearKey", "Sleutel wissen"),
            ("Settings.OutputFolder", "Uitvoermap"), ("Settings.Browse", "Bladeren"), ("Settings.Storage", "Opslag"),
            ("Settings.Output", "Uitvoer"), ("Settings.LanguageCard", "Taal"), ("Settings.Language", "Taal"),
            ("Settings.Updates", "Updates"), ("Settings.AutoUpdates", "Bij opstarten automatisch op updates controleren"),
            ("Settings.CurrentVersion", "Huidige versie: {0}"), ("Settings.CheckNow", "Nu controleren"), ("Settings.Advanced", "Geavanceerd"),
            ("Settings.ConnectionStatus", "Verbindingsstatus"), ("Settings.NotChecked", "Niet gecontroleerd"), ("Settings.Latency", "Latentie"),
            ("Settings.LastHealthCheck", "Laatste controle"), ("Settings.Save", "Opslaan"), ("Settings.Cancel", "Annuleren"),
            ("Settings.ResetEndpoint", "Resetten"), ("Settings.Checking", "Controleren..."), ("Settings.Connected", "Verbonden"),
            ("Settings.Unreachable", "Onbereikbaar"), ("Settings.Offline", "Offline"),
            ("Dash.DropPrimary", "Sleep bestand hierheen"), ("Dash.DropSecondary", "of klik om te bladeren  -  GameDB (.slt)  -  Profielgegevens  -  automatisch herkend"),
            ("Dash.FileInformation", "Bestandsinformatie"), ("Dash.Type", "Type"), ("Dash.Status", "Status"),
            ("Dash.Filename", "Bestandsnaam"), ("Dash.Integrity", "Integriteit"), ("Dash.Size", "Grootte"),
            ("Dash.Modified", "Gewijzigd"), ("Dash.NoFile", "Geen bestand geladen - sleep hierboven een GameDB, profiel, Method 22 ZIP of ini-bestand."),
            ("Dash.Actions", "Acties"), ("Dash.Decrypt", "Ontsleutelen"), ("Dash.ReEncrypt", "Opnieuw versleutelen"),
            ("Dash.Merge", "Samenvoegen"), ("Dash.Export", "Exporteren"), ("Dash.Output", "Uitvoer"),
            ("Dash.MergeTip", "Wijzigingen van een andere ontsleutelde GameDB toepassen op deze."),
            ("Dash.JobStatus", "Taakstatus"), ("Dash.Idle", "Inactief - wacht op bestand."),
            ("Dash.Results", "Resultaten"), ("Dash.Mode", "Modus"), ("Dash.Warnings", "Waarschuwingen"),
            ("Dash.NoResults", "Nog geen bewerking voltooid."), ("Dash.RecentFiles", "Recente bestanden"),
            ("Dash.ActivityLog", "Activiteitenlogboek"), ("Dash.ClearLog", "Log wissen"),
            ("Dash.SaveLog", "Log opslaan"), ("Dash.CopyLog", "Log kopiëren"),
            ("Dash.NoRecent", "(geen recente bestanden)")),

        ["pl-PL"] = Map(
            ("App.SettingsTitle", "{0} - Ustawienia"), ("Nav.Dashboard", "Panel"), ("Nav.SaveSwap", "Zamiana"),
            ("Nav.ProfileEditor", "Edytor profilu"), ("Nav.OlderForzaTech", "Starszy ForzaTech"), ("Nav.Settings", "Ustawienia"),
            ("Top.Settings", "Ustawienia"), ("Top.AboutTooltip", "O ForzaCryptoTool"), ("Top.BackendChecking", "Backend - Sprawdzanie"),
            ("Top.BackendConnected", "Backend - Połączono {0}ms"), ("Top.BackendOffline", "Backend - Offline"),
            ("Top.AdminElevated", "Admin - Podniesione"), ("Top.AdminStandard", "Admin - Standard"),
            ("Settings.Backend", "Backend"), ("Settings.Endpoint", "Endpoint"), ("Settings.TestConnection", "Test"),
            ("Settings.Source", "Źródło: {0}."), ("Settings.AppKey", "Klucz aplikacji"), ("Settings.ClearKey", "Wyczyść klucz"),
            ("Settings.OutputFolder", "Folder wyjściowy"), ("Settings.Browse", "Przeglądaj"), ("Settings.Storage", "Pamięć"),
            ("Settings.Output", "Wyjście"), ("Settings.LanguageCard", "Język"), ("Settings.Language", "Język"),
            ("Settings.Updates", "Aktualizacje"), ("Settings.AutoUpdates", "Automatycznie sprawdzaj aktualizacje przy starcie"),
            ("Settings.CurrentVersion", "Bieżąca wersja: {0}"), ("Settings.CheckNow", "Sprawdź teraz"), ("Settings.Advanced", "Zaawansowane"),
            ("Settings.ConnectionStatus", "Stan połączenia"), ("Settings.NotChecked", "Nie sprawdzono"), ("Settings.Latency", "Opóźnienie"),
            ("Settings.LastHealthCheck", "Ostatni test"), ("Settings.Save", "Zapisz"), ("Settings.Cancel", "Anuluj"),
            ("Settings.ResetEndpoint", "Resetuj"), ("Settings.Checking", "Sprawdzanie..."), ("Settings.Connected", "Połączono"),
            ("Settings.Unreachable", "Nieosiągalny"), ("Settings.Offline", "Offline"),
            ("Dash.DropPrimary", "Upuść plik tutaj"), ("Dash.DropSecondary", "lub kliknij, aby przeglądać  -  GameDB (.slt)  -  Dane profilu  -  wykrywanie automatyczne"),
            ("Dash.FileInformation", "Informacje o pliku"), ("Dash.Type", "Typ"), ("Dash.Status", "Stan"),
            ("Dash.Filename", "Nazwa pliku"), ("Dash.Integrity", "Integralność"), ("Dash.Size", "Rozmiar"),
            ("Dash.Modified", "Zmodyfikowano"), ("Dash.NoFile", "Nie załadowano pliku - upuść powyżej GameDB, profil, ZIP Method 22 lub plik ini."),
            ("Dash.Actions", "Akcje"), ("Dash.Decrypt", "Odszyfruj"), ("Dash.ReEncrypt", "Zaszyfruj ponownie"),
            ("Dash.Merge", "Scal"), ("Dash.Export", "Eksportuj"), ("Dash.Output", "Wyjście"),
            ("Dash.MergeTip", "Zastosuj zmiany z innej odszyfrowanej GameDB do tej."),
            ("Dash.JobStatus", "Stan zadania"), ("Dash.Idle", "Bezczynny - oczekiwanie na plik."),
            ("Dash.Results", "Wyniki"), ("Dash.Mode", "Tryb"), ("Dash.Warnings", "Ostrzeżenia"),
            ("Dash.NoResults", "Nie ukończono jeszcze żadnej operacji."), ("Dash.RecentFiles", "Ostatnie pliki"),
            ("Dash.ActivityLog", "Dziennik aktywności"), ("Dash.ClearLog", "Wyczyść dziennik"),
            ("Dash.SaveLog", "Zapisz dziennik"), ("Dash.CopyLog", "Kopiuj dziennik"),
            ("Dash.NoRecent", "(brak ostatnich plików)")),
    };

    private static readonly Dictionary<string, Dictionary<string, string>> ExtraStrings = new(StringComparer.OrdinalIgnoreCase)
    {
        [DefaultLanguageCode] = Map(
            ("Common.Browse", "Browse"), ("Common.Reset", "Reset"), ("Common.LaunchXbox", "Launch Xbox App"),
            ("Common.GrabXuid", "Grab XUID"), ("Common.Idle", "Idle"),
            ("SaveSwap.Warning", "Save swapping overwrites your ACTIVE save. A timestamped backup is made first and restored automatically if anything fails - make sure the Active Save is the file the game currently loads."),
            ("SaveSwap.Title", "Save Swap"), ("SaveSwap.Donor", "Donor save (decrypted or encrypted - swapped in)"),
            ("SaveSwap.Active", "Active save (overwritten - the save the game loads)"), ("SaveSwap.AutoDetect", "Auto-detect Active Save"),
            ("SaveSwap.TargetXuid", "Target XUID (decimal or 0x hex)"), ("SaveSwap.GrabHint", "Sign into the Xbox App with your target account, then Grab XUID."),
            ("SaveSwap.SwapSave", "Swap Save"), ("SaveSwap.Restore", "Restore Original Save"), ("SaveSwap.RestoreNoBackup", "Restore Original Save (no backup)"),
            ("SaveSwap.Result", "Swap Result"), ("SaveSwap.FillHint", "Fill in the fields and click Swap Save."), ("SaveSwap.Step", "Step"), ("SaveSwap.Detail", "Detail"),
            ("Profile.Title", "Profile Editor"), ("Profile.EncryptedProfile", "Encrypted C_ProfileData"), ("Profile.DecryptProfile", "Decrypt Profile"),
            ("Profile.AccountXuid", "Account XUID (decimal or 0x hex)"), ("Profile.PickEncrypted", "Pick an encrypted C_ProfileData, then Decrypt."),
            ("Profile.Encrypt", "Encrypt"), ("Profile.DecryptedProfile", "Decrypted Profile"), ("Profile.DecryptToView", "Decrypt a profile to view its properties."),
            ("Profile.Property", "Property"), ("Profile.Value", "Value"),
            ("Profile.Help", "1. Capture IVs and a matching C_ProfileData snapshot.\n2. Pick that snapshot, then Decrypt.\n3. Edit the XUID or editable fields, then Re-encrypt and Save."),
            ("ForzaTech.Target", "Target"), ("ForzaTech.Game", "Game"), ("ForzaTech.KeyType", "Key type"), ("ForzaTech.EncryptedFile", "Encrypted file"),
            ("ForzaTech.PickDecrypt", "Pick an encrypted file, choose the game + key type, then Decrypt."),
            ("ForzaTech.EditedPlaintext", "Edited plaintext"), ("ForzaTech.OriginalEncrypted", "Original encrypted file"),
            ("ForzaTech.PickReencrypt", "Pick the edited plaintext + the original encrypted file, then Re-encrypt.")),

        ["zh-CN"] = Map(
            ("Common.Browse", "浏览"), ("Common.Reset", "重置"), ("Common.LaunchXbox", "启动 Xbox 应用"), ("Common.GrabXuid", "抓取 XUID"), ("Common.Idle", "空闲"),
            ("SaveSwap.Warning", "存档替换会覆盖当前存档。工具会先创建带时间戳的备份，失败时会自动还原 - 请确认当前存档就是游戏正在加载的文件。"),
            ("SaveSwap.Title", "存档替换"), ("SaveSwap.Donor", "捐赠存档（已解密或已加密 - 将被替换进去）"), ("SaveSwap.Active", "当前存档（会被覆盖 - 游戏正在加载的存档）"),
            ("SaveSwap.AutoDetect", "自动检测当前存档"), ("SaveSwap.TargetXuid", "目标 XUID（十进制或 0x 十六进制）"), ("SaveSwap.GrabHint", "用目标账号登录 Xbox 应用，然后抓取 XUID。"),
            ("SaveSwap.SwapSave", "替换存档"), ("SaveSwap.Restore", "还原原始存档"), ("SaveSwap.RestoreNoBackup", "还原原始存档（无备份）"), ("SaveSwap.Result", "替换结果"),
            ("SaveSwap.FillHint", "填写字段并点击替换存档。"), ("SaveSwap.Step", "步骤"), ("SaveSwap.Detail", "详细信息"),
            ("Profile.Title", "档案编辑器"), ("Profile.EncryptedProfile", "已加密 C_ProfileData"), ("Profile.DecryptProfile", "解密档案"), ("Profile.AccountXuid", "账号 XUID（十进制或 0x 十六进制）"),
            ("Profile.PickEncrypted", "选择已加密 C_ProfileData，然后解密。"), ("Profile.Encrypt", "加密"), ("Profile.DecryptedProfile", "已解密档案"), ("Profile.DecryptToView", "解密档案以查看属性。"),
            ("Profile.Property", "属性"), ("Profile.Value", "值"),
            ("ForzaTech.Target", "目标"), ("ForzaTech.Game", "游戏"), ("ForzaTech.KeyType", "密钥类型"), ("ForzaTech.EncryptedFile", "已加密文件"),
            ("ForzaTech.PickDecrypt", "选择已加密文件、游戏和密钥类型，然后解密。"), ("ForzaTech.EditedPlaintext", "已编辑明文"), ("ForzaTech.OriginalEncrypted", "原始加密文件"),
            ("ForzaTech.PickReencrypt", "选择已编辑明文和原始加密文件，然后重新加密。")),

        ["nl-NL"] = Map(
            ("Common.Browse", "Bladeren"), ("Common.Reset", "Resetten"), ("Common.LaunchXbox", "Xbox-app starten"), ("Common.GrabXuid", "XUID ophalen"), ("Common.Idle", "Inactief"),
            ("SaveSwap.Warning", "Save wisselen overschrijft je ACTIEVE save. Er wordt eerst een back-up met tijdstempel gemaakt en bij fouten automatisch hersteld - controleer dat Actieve save het bestand is dat het spel laadt."),
            ("SaveSwap.Title", "Save wisselen"), ("SaveSwap.Donor", "Donor-save (ontsleuteld of versleuteld - wordt geplaatst)"), ("SaveSwap.Active", "Actieve save (wordt overschreven - de save die het spel laadt)"),
            ("SaveSwap.AutoDetect", "Actieve save automatisch zoeken"), ("SaveSwap.TargetXuid", "Doel-XUID (decimaal of 0x hex)"), ("SaveSwap.GrabHint", "Meld je aan bij de Xbox-app met het doelaccount en haal daarna de XUID op."),
            ("SaveSwap.SwapSave", "Save wisselen"), ("SaveSwap.Restore", "Originele save herstellen"), ("SaveSwap.RestoreNoBackup", "Originele save herstellen (geen back-up)"), ("SaveSwap.Result", "Wisselresultaat"),
            ("SaveSwap.FillHint", "Vul de velden in en klik op Save wisselen."), ("SaveSwap.Step", "Stap"), ("SaveSwap.Detail", "Detail"),
            ("Profile.Title", "Profieleditor"), ("Profile.EncryptedProfile", "Versleutelde C_ProfileData"), ("Profile.DecryptProfile", "Profiel ontsleutelen"), ("Profile.AccountXuid", "Account-XUID (decimaal of 0x hex)"),
            ("Profile.PickEncrypted", "Kies een versleutelde C_ProfileData en ontsleutel."), ("Profile.Encrypt", "Versleutelen"), ("Profile.DecryptedProfile", "Ontsleuteld profiel"), ("Profile.DecryptToView", "Ontsleutel een profiel om eigenschappen te bekijken."),
            ("Profile.Property", "Eigenschap"), ("Profile.Value", "Waarde"),
            ("ForzaTech.Target", "Doel"), ("ForzaTech.Game", "Spel"), ("ForzaTech.KeyType", "Sleuteltype"), ("ForzaTech.EncryptedFile", "Versleuteld bestand"),
            ("ForzaTech.PickDecrypt", "Kies een versleuteld bestand, spel en sleuteltype en ontsleutel."), ("ForzaTech.EditedPlaintext", "Bewerkte platte tekst"), ("ForzaTech.OriginalEncrypted", "Origineel versleuteld bestand"),
            ("ForzaTech.PickReencrypt", "Kies de bewerkte platte tekst en het originele versleutelde bestand en versleutel opnieuw.")),

        ["fr-FR"] = Map(
            ("Common.Browse", "Parcourir"), ("Common.Reset", "Réinitialiser"), ("Common.LaunchXbox", "Lancer Xbox"), ("Common.GrabXuid", "Lire le XUID"), ("Common.Idle", "Inactif"),
            ("SaveSwap.Warning", "L'échange de sauvegarde écrase votre sauvegarde ACTIVE. Une sauvegarde horodatée est créée d'abord et restaurée si une erreur survient - vérifiez que la sauvegarde active est celle chargée par le jeu."),
            ("SaveSwap.Title", "Échange de sauvegarde"), ("SaveSwap.Donor", "Sauvegarde donneuse (déchiffrée ou chiffrée - importée)"), ("SaveSwap.Active", "Sauvegarde active (écrasée - celle chargée par le jeu)"),
            ("SaveSwap.AutoDetect", "Détecter la sauvegarde active"), ("SaveSwap.TargetXuid", "XUID cible (décimal ou hex 0x)"), ("SaveSwap.GrabHint", "Connectez-vous à Xbox avec le compte cible, puis lisez le XUID."),
            ("SaveSwap.SwapSave", "Échanger"), ("SaveSwap.Restore", "Restaurer l'original"), ("SaveSwap.RestoreNoBackup", "Restaurer l'original (pas de sauvegarde)"), ("SaveSwap.Result", "Résultat"),
            ("SaveSwap.FillHint", "Remplissez les champs puis cliquez sur Échanger."), ("SaveSwap.Step", "Étape"), ("SaveSwap.Detail", "Détail"),
            ("Profile.Title", "Éditeur de profil"), ("Profile.EncryptedProfile", "C_ProfileData chiffré"), ("Profile.DecryptProfile", "Déchiffrer le profil"), ("Profile.AccountXuid", "XUID du compte (décimal ou hex 0x)"),
            ("Profile.PickEncrypted", "Choisissez un C_ProfileData chiffré, puis déchiffrez."), ("Profile.Encrypt", "Chiffrer"), ("Profile.DecryptedProfile", "Profil déchiffré"), ("Profile.DecryptToView", "Déchiffrez un profil pour voir ses propriétés."),
            ("Profile.Property", "Propriété"), ("Profile.Value", "Valeur"),
            ("ForzaTech.Target", "Cible"), ("ForzaTech.Game", "Jeu"), ("ForzaTech.KeyType", "Type de clé"), ("ForzaTech.EncryptedFile", "Fichier chiffré"),
            ("ForzaTech.PickDecrypt", "Choisissez un fichier chiffré, le jeu et le type de clé, puis déchiffrez."), ("ForzaTech.EditedPlaintext", "Texte clair modifié"), ("ForzaTech.OriginalEncrypted", "Fichier chiffré original"),
            ("ForzaTech.PickReencrypt", "Choisissez le texte clair modifié et le fichier chiffré original, puis rechiffrez.")),

        ["es-ES"] = Map(
            ("Common.Browse", "Examinar"), ("Common.Reset", "Restablecer"), ("Common.LaunchXbox", "Abrir Xbox"), ("Common.GrabXuid", "Obtener XUID"), ("Common.Idle", "Inactivo"),
            ("SaveSwap.Warning", "El cambio de guardado sobrescribe tu guardado ACTIVO. Primero se crea una copia con fecha y se restaura si algo falla - confirma que el guardado activo es el que carga el juego."),
            ("SaveSwap.Title", "Cambio de guardado"), ("SaveSwap.Donor", "Guardado donante (descifrado o cifrado - se insertará)"), ("SaveSwap.Active", "Guardado activo (se sobrescribe - el que carga el juego)"),
            ("SaveSwap.AutoDetect", "Detectar guardado activo"), ("SaveSwap.TargetXuid", "XUID destino (decimal o hex 0x)"), ("SaveSwap.GrabHint", "Inicia sesión en Xbox con la cuenta destino y obtén el XUID."),
            ("SaveSwap.SwapSave", "Cambiar guardado"), ("SaveSwap.Restore", "Restaurar original"), ("SaveSwap.RestoreNoBackup", "Restaurar original (sin copia)"), ("SaveSwap.Result", "Resultado"),
            ("SaveSwap.FillHint", "Rellena los campos y haz clic en Cambiar guardado."), ("SaveSwap.Step", "Paso"), ("SaveSwap.Detail", "Detalle"),
            ("Profile.Title", "Editor de perfil"), ("Profile.EncryptedProfile", "C_ProfileData cifrado"), ("Profile.DecryptProfile", "Descifrar perfil"), ("Profile.AccountXuid", "XUID de cuenta (decimal o hex 0x)"),
            ("Profile.PickEncrypted", "Elige un C_ProfileData cifrado y descífralo."), ("Profile.Encrypt", "Cifrar"), ("Profile.DecryptedProfile", "Perfil descifrado"), ("Profile.DecryptToView", "Descifra un perfil para ver sus propiedades."),
            ("Profile.Property", "Propiedad"), ("Profile.Value", "Valor"),
            ("ForzaTech.Target", "Destino"), ("ForzaTech.Game", "Juego"), ("ForzaTech.KeyType", "Tipo de clave"), ("ForzaTech.EncryptedFile", "Archivo cifrado"),
            ("ForzaTech.PickDecrypt", "Elige un archivo cifrado, juego y tipo de clave, y descifra."), ("ForzaTech.EditedPlaintext", "Texto plano editado"), ("ForzaTech.OriginalEncrypted", "Archivo cifrado original"),
            ("ForzaTech.PickReencrypt", "Elige el texto plano editado y el archivo cifrado original, y vuelve a cifrar.")),

        ["de-DE"] = Map(
            ("Common.Browse", "Durchsuchen"), ("Common.Reset", "Zurücksetzen"), ("Common.LaunchXbox", "Xbox-App starten"), ("Common.GrabXuid", "XUID holen"), ("Common.Idle", "Leerlauf"),
            ("SaveSwap.Warning", "Der Save-Tausch überschreibt den AKTIVEN Save. Zuerst wird ein Zeitstempel-Backup erstellt und bei Fehlern automatisch wiederhergestellt - prüfen Sie, dass der aktive Save vom Spiel geladen wird."),
            ("SaveSwap.Title", "Save-Tausch"), ("SaveSwap.Donor", "Donor-Save (entschlüsselt oder verschlüsselt - wird eingesetzt)"), ("SaveSwap.Active", "Aktiver Save (wird überschrieben - vom Spiel geladen)"),
            ("SaveSwap.AutoDetect", "Aktiven Save erkennen"), ("SaveSwap.TargetXuid", "Ziel-XUID (dezimal oder 0x hex)"), ("SaveSwap.GrabHint", "Mit dem Zielkonto in der Xbox-App anmelden, dann XUID holen."),
            ("SaveSwap.SwapSave", "Save tauschen"), ("SaveSwap.Restore", "Original wiederherstellen"), ("SaveSwap.RestoreNoBackup", "Original wiederherstellen (kein Backup)"), ("SaveSwap.Result", "Tausch-Ergebnis"),
            ("SaveSwap.FillHint", "Felder ausfüllen und auf Save tauschen klicken."), ("SaveSwap.Step", "Schritt"), ("SaveSwap.Detail", "Detail"),
            ("Profile.Title", "Profil-Editor"), ("Profile.EncryptedProfile", "Verschlüsselte C_ProfileData"), ("Profile.DecryptProfile", "Profil entschlüsseln"), ("Profile.AccountXuid", "Konto-XUID (dezimal oder 0x hex)"),
            ("Profile.PickEncrypted", "Verschlüsselte C_ProfileData wählen und entschlüsseln."), ("Profile.Encrypt", "Verschlüsseln"), ("Profile.DecryptedProfile", "Entschlüsseltes Profil"), ("Profile.DecryptToView", "Profil entschlüsseln, um Eigenschaften zu sehen."),
            ("Profile.Property", "Eigenschaft"), ("Profile.Value", "Wert"),
            ("ForzaTech.Target", "Ziel"), ("ForzaTech.Game", "Spiel"), ("ForzaTech.KeyType", "Schlüsseltyp"), ("ForzaTech.EncryptedFile", "Verschlüsselte Datei"),
            ("ForzaTech.PickDecrypt", "Verschlüsselte Datei, Spiel und Schlüsseltyp wählen, dann entschlüsseln."), ("ForzaTech.EditedPlaintext", "Bearbeiteter Klartext"), ("ForzaTech.OriginalEncrypted", "Originale verschlüsselte Datei"),
            ("ForzaTech.PickReencrypt", "Bearbeiteten Klartext und originale verschlüsselte Datei wählen, dann neu verschlüsseln.")),

        ["it-IT"] = Map(
            ("Common.Browse", "Sfoglia"), ("Common.Reset", "Reimposta"), ("Common.LaunchXbox", "Avvia Xbox"), ("Common.GrabXuid", "Leggi XUID"), ("Common.Idle", "Inattivo"),
            ("SaveSwap.Warning", "Lo scambio salvataggio sovrascrive il salvataggio ATTIVO. Prima viene creato un backup con data e ripristinato se qualcosa fallisce - verifica che sia il file caricato dal gioco."),
            ("SaveSwap.Title", "Scambio salvataggio"), ("SaveSwap.Donor", "Salvataggio donatore (decifrato o cifrato - verrà inserito)"), ("SaveSwap.Active", "Salvataggio attivo (sovrascritto - quello caricato dal gioco)"),
            ("SaveSwap.AutoDetect", "Rileva salvataggio attivo"), ("SaveSwap.TargetXuid", "XUID destinazione (decimale o hex 0x)"), ("SaveSwap.GrabHint", "Accedi all'app Xbox con l'account destinazione, poi leggi lo XUID."),
            ("SaveSwap.SwapSave", "Scambia salvataggio"), ("SaveSwap.Restore", "Ripristina originale"), ("SaveSwap.RestoreNoBackup", "Ripristina originale (nessun backup)"), ("SaveSwap.Result", "Risultato"),
            ("SaveSwap.FillHint", "Compila i campi e fai clic su Scambia salvataggio."), ("SaveSwap.Step", "Passo"), ("SaveSwap.Detail", "Dettaglio"),
            ("Profile.Title", "Editor profilo"), ("Profile.EncryptedProfile", "C_ProfileData cifrato"), ("Profile.DecryptProfile", "Decifra profilo"), ("Profile.AccountXuid", "XUID account (decimale o hex 0x)"),
            ("Profile.PickEncrypted", "Scegli un C_ProfileData cifrato, poi decifra."), ("Profile.Encrypt", "Cifra"), ("Profile.DecryptedProfile", "Profilo decifrato"), ("Profile.DecryptToView", "Decifra un profilo per vedere le proprietà."),
            ("Profile.Property", "Proprietà"), ("Profile.Value", "Valore"),
            ("ForzaTech.Target", "Destinazione"), ("ForzaTech.Game", "Gioco"), ("ForzaTech.KeyType", "Tipo chiave"), ("ForzaTech.EncryptedFile", "File cifrato"),
            ("ForzaTech.PickDecrypt", "Scegli un file cifrato, gioco e tipo chiave, poi decifra."), ("ForzaTech.EditedPlaintext", "Testo in chiaro modificato"), ("ForzaTech.OriginalEncrypted", "File cifrato originale"),
            ("ForzaTech.PickReencrypt", "Scegli il testo modificato e il file cifrato originale, poi ricifra.")),

        ["pt-PT"] = Map(
            ("Common.Browse", "Procurar"), ("Common.Reset", "Repor"), ("Common.LaunchXbox", "Abrir Xbox"), ("Common.GrabXuid", "Obter XUID"), ("Common.Idle", "Inativo"),
            ("SaveSwap.Warning", "A troca de save substitui o save ATIVO. Primeiro é criada uma cópia com data e restaurada se algo falhar - confirme que o save ativo é o ficheiro carregado pelo jogo."),
            ("SaveSwap.Title", "Troca de save"), ("SaveSwap.Donor", "Save doador (desencriptado ou encriptado - será aplicado)"), ("SaveSwap.Active", "Save ativo (será substituído - o que o jogo carrega)"),
            ("SaveSwap.AutoDetect", "Detetar save ativo"), ("SaveSwap.TargetXuid", "XUID alvo (decimal ou hex 0x)"), ("SaveSwap.GrabHint", "Inicie sessão na app Xbox com a conta alvo e obtenha o XUID."),
            ("SaveSwap.SwapSave", "Trocar save"), ("SaveSwap.Restore", "Restaurar original"), ("SaveSwap.RestoreNoBackup", "Restaurar original (sem cópia)"), ("SaveSwap.Result", "Resultado"),
            ("SaveSwap.FillHint", "Preencha os campos e clique em Trocar save."), ("SaveSwap.Step", "Passo"), ("SaveSwap.Detail", "Detalhe"),
            ("Profile.Title", "Editor de perfil"), ("Profile.EncryptedProfile", "C_ProfileData encriptado"), ("Profile.DecryptProfile", "Desencriptar perfil"), ("Profile.AccountXuid", "XUID da conta (decimal ou hex 0x)"),
            ("Profile.PickEncrypted", "Escolha um C_ProfileData encriptado e desencripte."), ("Profile.Encrypt", "Encriptar"), ("Profile.DecryptedProfile", "Perfil desencriptado"), ("Profile.DecryptToView", "Desencripte um perfil para ver propriedades."),
            ("Profile.Property", "Propriedade"), ("Profile.Value", "Valor"),
            ("ForzaTech.Target", "Alvo"), ("ForzaTech.Game", "Jogo"), ("ForzaTech.KeyType", "Tipo de chave"), ("ForzaTech.EncryptedFile", "Ficheiro encriptado"),
            ("ForzaTech.PickDecrypt", "Escolha um ficheiro encriptado, jogo e tipo de chave, depois desencripte."), ("ForzaTech.EditedPlaintext", "Texto editado"), ("ForzaTech.OriginalEncrypted", "Ficheiro encriptado original"),
            ("ForzaTech.PickReencrypt", "Escolha o texto editado e o ficheiro encriptado original, depois reencripte.")),

        ["pl-PL"] = Map(
            ("Common.Browse", "Przeglądaj"), ("Common.Reset", "Resetuj"), ("Common.LaunchXbox", "Uruchom Xbox"), ("Common.GrabXuid", "Pobierz XUID"), ("Common.Idle", "Bezczynny"),
            ("SaveSwap.Warning", "Zamiana zapisu nadpisuje AKTYWNY zapis. Najpierw tworzona jest kopia z datą i automatycznie przywracana przy błędzie - upewnij się, że aktywny zapis jest plikiem ładowanym przez grę."),
            ("SaveSwap.Title", "Zamiana zapisu"), ("SaveSwap.Donor", "Zapis dawcy (odszyfrowany lub zaszyfrowany - zostanie użyty)"), ("SaveSwap.Active", "Aktywny zapis (zostanie nadpisany - ładowany przez grę)"),
            ("SaveSwap.AutoDetect", "Wykryj aktywny zapis"), ("SaveSwap.TargetXuid", "Docelowy XUID (dziesiętnie lub hex 0x)"), ("SaveSwap.GrabHint", "Zaloguj się w aplikacji Xbox na konto docelowe, potem pobierz XUID."),
            ("SaveSwap.SwapSave", "Zamień zapis"), ("SaveSwap.Restore", "Przywróć oryginał"), ("SaveSwap.RestoreNoBackup", "Przywróć oryginał (brak kopii)"), ("SaveSwap.Result", "Wynik zamiany"),
            ("SaveSwap.FillHint", "Wypełnij pola i kliknij Zamień zapis."), ("SaveSwap.Step", "Krok"), ("SaveSwap.Detail", "Szczegół"),
            ("Profile.Title", "Edytor profilu"), ("Profile.EncryptedProfile", "Zaszyfrowany C_ProfileData"), ("Profile.DecryptProfile", "Odszyfruj profil"), ("Profile.AccountXuid", "XUID konta (dziesiętnie lub hex 0x)"),
            ("Profile.PickEncrypted", "Wybierz zaszyfrowany C_ProfileData i odszyfruj."), ("Profile.Encrypt", "Zaszyfruj"), ("Profile.DecryptedProfile", "Odszyfrowany profil"), ("Profile.DecryptToView", "Odszyfruj profil, aby zobaczyć właściwości."),
            ("Profile.Property", "Właściwość"), ("Profile.Value", "Wartość"),
            ("ForzaTech.Target", "Cel"), ("ForzaTech.Game", "Gra"), ("ForzaTech.KeyType", "Typ klucza"), ("ForzaTech.EncryptedFile", "Zaszyfrowany plik"),
            ("ForzaTech.PickDecrypt", "Wybierz zaszyfrowany plik, grę i typ klucza, potem odszyfruj."), ("ForzaTech.EditedPlaintext", "Edytowany tekst jawny"), ("ForzaTech.OriginalEncrypted", "Oryginalny zaszyfrowany plik"),
            ("ForzaTech.PickReencrypt", "Wybierz edytowany tekst jawny i oryginalny zaszyfrowany plik, potem zaszyfruj ponownie.")),
    };

    public static string NormalizeLanguageCode(string? code) =>
        SupportedLanguages.Any(language => string.Equals(language.Code, code, StringComparison.OrdinalIgnoreCase))
            ? SupportedLanguages.First(language => string.Equals(language.Code, code, StringComparison.OrdinalIgnoreCase)).Code
            : DefaultLanguageCode;

    public static string T(AppSettings settings, string key, params object[] args) =>
        T(settings.LanguageCode, key, args);

    public static string T(string? languageCode, string key, params object[] args)
    {
        var normalized = NormalizeLanguageCode(languageCode);
        var text = Strings.TryGetValue(normalized, out var language) && language.TryGetValue(key, out var localized)
            ? localized
            : ExtraStrings.TryGetValue(normalized, out var extras) && extras.TryGetValue(key, out var extra)
                ? extra
                : Strings[DefaultLanguageCode].TryGetValue(key, out var fallback)
                    ? fallback
                    : ExtraStrings[DefaultLanguageCode].TryGetValue(key, out var extraFallback)
                        ? extraFallback
                        : key;
        return args.Length == 0 ? text : string.Format(text, args);
    }

    private static Dictionary<string, string> Map(params (string Key, string Value)[] values) =>
        values.ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.Ordinal);
}
