<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>ForzaCryptoTool</RootNamespace>
    <AssemblyName>ForzaCryptoTool</AssemblyName>
    <AssemblyTitle>Forza Crypto Tool</AssemblyTitle>
    <Product>Forza Crypto Tool</Product>
    <Version>3.1.0</Version>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>

    <StartupObject>ForzaCryptoTool.EntryPoint</StartupObject>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);DEV_BUILD</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForzaCryptoTool.Core\ForzaCryptoTool.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="System.Net.Http" />

    <Using Include="System.Windows.Input" />
  </ItemGroup>

</Project>
