<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ForzaCryptoTool</RootNamespace>
    <AssemblyName>ForzaCryptoTool.Core</AssemblyName>
    <Version>3.1.0</Version>

    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.30" />

    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />

    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ForzaCryptoTool" />
    <InternalsVisibleTo Include="forzacrypto" />
  </ItemGroup>

</Project>
